<a href="https://colab.research.google.com/github/LearnByDoing2024/Youtube/blob/main/Episode2%2C_numpy_intro_transformerplayground_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Vector
A **vector** is a 1-dimensional array of numbers. It can be thought of as a point in space that has both **magnitude** and **direction**.

For example, a 2D vector looks like this:  
$$ \mathbf{v} = \begin{bmatrix} 3 \\ 4 \end{bmatrix} $$
- Magnitude: $$ \sqrt{3^2 + 4^2} = 5 $$

### Array
An **array** is a collection of numbers or values arranged in a specific order. It can be 1-dimensional (like a vector) or multi-dimensional.

- 1D array: $$[1, 2, 3]$$
- 2D array (matrix): $$[[1, 2], [3, 4]]$$

### Matrix
A **matrix** is a 2-dimensional array of numbers arranged in rows and columns. It's used in various mathematical operations like transformations, solving equations, and more.

For example:
$$ \mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} $$

### Determinant
The **determinant** is a special number that can be calculated from a square matrix. It gives information about the matrix, such as whether it is invertible or the scale of transformation.

For a 2x2 matrix:
$$ \text{det}(A) = ad - bc $$

For the matrix:
$$ \mathbf{A} = \begin{bmatrix} a & b \\ c & d \end{bmatrix} $$

The determinant is $$ \text{det}(A) = ad - bc $$. If the determinant is 0, the matrix is **singular** (not invertible).

# NumPy from Beginner to Advanced
This notebook will guide you through key features of NumPy, from basic array operations to advanced linear algebra.


## 1. Beginner Level

### 1.1 Introduction to NumPy
NumPy is a powerful library for numerical computations in Python. It allows efficient handling of arrays and matrices.


In [2]:
# Importing NumPy
import numpy as np

# Creating a simple array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


### 1.2 Basic Array Operations
Array operations such as indexing, slicing, and reshaping are fundamental to using NumPy.

In [4]:
# Indexing and slicing
arr_slice = arr[1:4]
print("Sliced Array:", arr_slice)

# Reshaping
reshaped_arr = np.reshape(arr, (5, 1))
print("Reshaped Array:\n", reshaped_arr)

Sliced Array: [2 3 4]
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


## 2. Intermediate Level

### 2.1 Mathematical Operations
NumPy supports element-wise operations and broadcasting, allowing efficient operations over arrays.

In [5]:
# Element-wise addition
arr2 = np.array([10, 20, 30, 40, 50])
sum_arr = arr + arr2
print("Sum of arrays:", sum_arr)

# Broadcasting example
broadcast_arr = arr + 10
print("Broadcasted Array:", broadcast_arr)

Sum of arrays: [11 22 33 44 55]
Broadcasted Array: [11 12 13 14 15]


### 2.2 Statistical Functions
NumPy provides a wide range of statistical functions, such as calculating the mean and standard deviation.

In [4]:
# Statistical operations
mean_value = np.mean(arr)
std_dev = np.std(arr)
print("Mean:", mean_value)
print("Standard Deviation:", std_dev)

Mean: 3.0
Standard Deviation: 1.4142135623730951


## 3. Advanced Level

### 3.1 Working with Multidimensional Arrays
Learn how to create and manipulate multidimensional arrays, also known as matrices.

In [5]:
# Creating a 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array (Matrix):\n", matrix)

# Matrix multiplication
matrix2 = np.array([[7, 8], [9, 10], [11, 12]])
product = np.dot(matrix, matrix2)
print("Matrix Product:\n", product)

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]]
Matrix Product:
 [[ 58  64]
 [139 154]]


### 3.2 Random Number Generation
NumPy can generate random numbers, useful for simulations and modeling.


In [6]:
# Generating random numbers
random_arr = np.random.random((3, 3))
print("Random Array:\n", random_arr)

# Random integers
random_ints = np.random.randint(1, 100, size=(3, 3))
print("Random Integers:\n", random_ints)

Random Array:
 [[0.74353091 0.19679905 0.78589128]
 [0.09581776 0.30821031 0.03616223]
 [0.95344653 0.15733689 0.06067068]]
Random Integers:
 [[66  2 32]
 [15 48 18]
 [53  7 53]]


### 3.3 Linear Algebra and Advanced Functions
NumPy's linear algebra capabilities include solving systems of equations and computing determinants.

In [7]:
# Solving systems of equations
coeff_matrix = np.array([[3, 1], [1, 2]])
const_matrix = np.array([9, 8])
solutions = np.linalg.solve(coeff_matrix, const_matrix)
print("Solutions to the system of equations:", solutions)

# Determinant of a matrix
det = np.linalg.det(coeff_matrix)
print("Determinant of the matrix:", det)

Solutions to the system of equations: [2. 3.]
Determinant of the matrix: 5.000000000000001


#### Explanation:
- **`coeff_matrix`** represents the coefficients of the variables in the system of equations.
  - This matrix represents the system:
    $$
    3x + 1y = 9$$
    $$1x + 2y = 8
    $$
- **`const_matrix`** is the constants on the right-hand side of the equations.
- **`np.linalg.solve(coeff_matrix, const_matrix)`** finds the values of `x` and `y` that satisfy both equations simultaneously. This is done using linear algebra techniques like Gaussian elimination.
- The solution will be the values of `x` and `y`.

Output:
```
Solutions to the system of equations: [2. 3.]
```
So, $$ x = 2 $$ and $$ y = 3 $$.

### 2. Determinant of a Matrix
The **determinant** of a matrix is a special number that gives important information about the matrix, such as whether the matrix is invertible or how much it scales the space it acts on. NumPy provides `np.linalg.det()` to calculate the determinant of a matrix.

#### Explanation:
- **`np.linalg.det(coeff_matrix)`** calculates the determinant of the coefficient matrix.
  - For a 2x2 matrix $$
  \mathbf{A} = \begin{bmatrix} a & b \\ c & d \end{bmatrix}
  $$
  The determinant is given by:
  $$
  \text{det}(A) = ad - bc
  $$
  In this case, for the matrix:
  $$
  \begin{bmatrix} 3 & 1 \\ 1 & 2 \end{bmatrix}
  $$
  The determinant is:
  $$
  \text{det} = (3 \times 2) - (1 \times 1) = 6 - 1 = 5
  $$

Output:
```
Determinant of the matrix: 5.000000000000001
```
The determinant is 5, which is non-zero, meaning the matrix is invertible and the system of equations has a unique solution.

## Conclusion
NumPy is a versatile tool that boosts the performance of mathematical computations in Python. Continue exploring its documentation for more advanced topics.